// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfRjwWcUInbj2Ax3uaY_vZANp-pr2ZO0A',
    appId: '1:1009894025358:web:7527d47c194010d17d81df',
    messagingSenderId: '1009894025358',
    projectId: 'flutter-to-buy-2',
    authDomain: 'flutter-to-buy-2.firebaseapp.com',
    storageBucket: 'flutter-to-buy-2.appspot.com',
    measurementId: 'G-YSQZPCV48J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1POIPoNtJ-9kXpkaG6elHTTEWFMT1XLk',
    appId: '1:1009894025358:android:efe134f4e6c216737d81df',
    messagingSenderId: '1009894025358',
    projectId: 'flutter-to-buy-2',
    storageBucket: 'flutter-to-buy-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0c4b_unyWsSE0bManFm1f2G5AKbeBeY',
    appId: '1:1009894025358:ios:485574fe905efdb67d81df',
    messagingSenderId: '1009894025358',
    projectId: 'flutter-to-buy-2',
    storageBucket: 'flutter-to-buy-2.appspot.com',
    iosBundleId: 'com.jerry.tobuylist.toBuyList',
  );
}
